CREATE DATABASE airbnb;
USE airbnb;

--Creating a table listings table
CREATE TABLE airbnb_listings (
   id NUMERIC(20, 0),
    name VARCHAR(255),
    host_id INT,
    host_name VARCHAR(255),
    neighbourhood_group VARCHAR(255),
    neighbourhood VARCHAR(255),
    latitude DECIMAL(12, 8),
    longitude DECIMAL(12, 8),
    room_type VARCHAR(255),
    price INT,
    minimum_nights INT,
    number_of_reviews INT,
    last_review DATE,
    reviews_per_month DECIMAL(10, 2),
    calculated_host_listings_count INT,
    availability_365 INT,
    number_of_reviews_ltm INT,
    license VARCHAR(255)
);


---creating pricing table
CREATE TABLE airbnb_pricing (
    listing_id INT,
    date DATE,
    available VARCHAR(10),
    price DECIMAL(10, 2),
    adjusted_price DECIMAL(10, 2),
    minimum_nights INT,
    maximum_nights INT,
    PRIMARY KEY (listing_id, date)
);


--Creating Reviews table
CREATE TABLE airbnb_reviews (
    listing_id BIGINT,
    id BIGINT,
    date DATE,
    reviewer_id INT,
    reviewer_name VARCHAR(255),
    comments TEXT
);

--inserting into listing table
BULK INSERT airbnb_listings
FROM 'C:\Getting Started with SQL Course\listings.csv'
WITH(
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    FIRSTROW = 2,
    FORMAT = 'CSV'
);

SELECT * FROM airbnb_listings;

--inserting into pricing tablE
BULK INSERT airbnb_pricing
FROM 'C:\Getting Started with SQL Course\pricing.csv'
WITH(
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    FIRSTROW = 2,
    FORMAT = 'CSV'
);

SELECT * FROM airbnb_pricing;

--inserting into review table
BULK INSERT airbnb_reviews
FROM 'C:\Getting Started with SQL Course\reviews.csv'
WITH(
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    FIRSTROW = 2,
    FORMAT = 'CSV'
);

SELECT * FROM airbnb_reviews;

--Case Study / Capstone Project

-- Q1 & Q2: Find the neighborhood with the highest total revenue and the average price per listing
SELECT 
    neighbourhood,
    SUM(price) total_revenue,
    AVG(price) avg_price
FROM airbnb_listings
GROUP BY neighbourhood
ORDER BY total_revenue DESC;

-- Q3: Count the occurrences of the word "comfortable" in the comment's column

SELECT 
    COUNT(*) count_comfortable
FROM airbnb_reviews
WHERE comments LIKE '%comfortable%';

-- Q4: Identify listings with a high proportion of positive reviews(comments with “great”, “comfortable” and “good”)

SELECT
    listing_id,
    comments
FROM airbnb_reviews
WHERE comments LIKE '%great%'
    OR comments LIKE 'comments'
    OR comments LIKE '%good%';


-- Q5: Calculate the total revenue generated by each host for listings that were last reviewed within the past one year
SELECT 
    host_name,
    SUM(price) total_revenue
FROM airbnb_listings
WHERE last_review >= DATEADD(YEAR, -1, GETDATE())
GROUP BY host_name;

-- Q6: Find hosts with the name ‘Stan’, regardless of capitalization
SELECT 
    host_name
FROM airbnb_listings
WHERE host_name LIKE UPPER('%Stan') 
    OR host_name LIKE LOWER('%Stan');


-- Q7: Calculate the total revenue generated by listings with a price above $700
SELECT 
    listing_id,
    SUM(price) total_revenue
FROM airbnb_pricing
WHERE price > 700
GROUP BY listing_id;


-- Q8: Find the most reviewed listing
SELECT TOP 1
    listing_id,
    COUNT(CAST(comments AS VARCHAR(MAX))) total_review
FROM airbnb_reviews
GROUP BY listing_id;

-- Q9: Find listings that were last reviewed in the last quarter of 2022
SELECT 
    id
FROM airbnb_listings
WHERE DATEPART(QUARTER, last_review) = 4
    AND YEAR(last_review) = 2022;


-- Q10: Calculate the total revenue generated for each listing, categorizing them as "high-priced" or "low-priced" based on their price relative to the average price for their neighborhood
WITH neighborhood_avg AS (
    SELECT 
        neighbourhood,
        AVG(price) AS avg_price
    FROM airbnb_listings
    GROUP BY neighbourhood
)
SELECT 
    a.id,
    SUM(a.price) AS total_revenue,
    CASE
        WHEN a.price > n.avg_price THEN 'High_Priced'
        ELSE 'Low_Priced'
    END AS category
FROM airbnb_listings a
JOIN neighborhood_avg n
    ON a.neighbourhood = n.neighbourhood
GROUP BY a.id, a.price, n.avg_price;
